### ISSUE TITLE
An error occurs while type class are generating.

### ISSUE THREAD

**Issue by mahmutbayri** [marc1706/fast-image-size#18]
At this line https://github.com/marc1706/fast-image-size/blob/master/lib/FastImageSize.php#L81 ucfirst function is used to generate class name. ico, iff word cant be converted correcly by ucfirst, and it cause a class not found error. They are converted to ico, iff (as same name). 
mb_convert_case function works fine.
May be we should use like this.
mb_convert_case($str, MB_CASE_TITLE, "UTF-8");

I am going to send a PR. Do you have any comment for this issue. 

https://github.com/Lullabot/amp-library package uses your package. 3-5 monts ago, it used to work without any problem.

Thanks.

**Comment by marc1706** [comment]
Did you recently change the PHP version or config you're using?

**Comment by mahmutbayri** [comment]
I'm using php 7.0.8. Today i am going to test on a very basic project, and i will share the results here.

Thanks.

**Comment by mahmutbayri** [comment]
Hi,
I have found the problem and a solution.

The problem is appear when setlocate is changed.

Test1 (Wrong)
```
setlocale(LC_CTYPE, 'tr_TR.UTF-8');

echo ucfirst("icon");
echo "<br />";
echo mb_convert_case('icon', MB_CASE_TITLE, "UTF-8");
```
Output:
icon
Icon

Test 2 (Correct)

```
echo ucfirst("icon");
echo "<br />";
echo mb_convert_case('icon', MB_CASE_TITLE, "UTF-8");
```
Output:
Icon
Icon

We shoud use mb_convert_case because mb_convert_case is not affected by locale settings.

http://php.net/ says:

> By contrast to the standard case folding functions such as strtolower() and strtoupper(), case folding is performed on the basis of the Unicode character properties. Thus the behaviour of this function is not affected by locale settings and it can convert any characters that have 'alphabetic' property, such as A-umlaut (Ä).
> 
> For more information about the Unicode properties, please see » http://www.unicode.org/unicode/reports/tr21/.

Referance: http://php.net/manual/en/function.mb-convert-case.php#refsect1-function.mb-convert-case-unicode

Thanks.

**Comment by marc1706** [comment]
Ok, thanks for further looking into this.

**Comment by loumray** [comment]
Hi, these tests results do not make much sense.

Was this real hard coded tests or some manually written translation of more complex tests?

If you "hard code test" ucfirst("icon") on different locale you will always get the correct "Icon" simply because there is no utf-8 sensitive character in this string.

ucfirst("écon") might return the unexpected "écon" depending on system locale, but "icon" never fails and always returns "Icon". Therefore mbstring is not needed for that.

In this code, the list of string to "ucfirst" are listed in the supportedTypes array and do not contain any sensitive character that will fail to be capitalized.

The UTF-8/locale issue here seems more likely related to the regex used in the preg functions to match the file extensions. The regex used is not using [unicode matching](http://php.net/manual/en/regexp.reference.unicode.php). [a-z0-9-.] will only match ASCII character. These function are used on
https://github.com/marc1706/fast-image-size/blob/master/lib/FastImageSize.php#L106 and  https://github.com/marc1706/fast-image-size/blob/master/lib/FastImageSize.php#L112

I suggest to change the regex to use unicode matching or juste replace any preg extension matching and use the locale "aware" pathinfo function to extract file extension. Something like:
`$extension = strtolower(pathinfo(parse_url($file, PHP_URL_PATH), PATHINFO_EXTENSION));`

This should work for URL and server files.

Hope that helps.

Related reference: https://stackoverflow.com/questions/1467114/how-locale-aware-is-preg-replace-in-php
